import Head from "next/head";
import { FC } from "react";
import { Layout, LayoutType } from "../components/UI";

const Home:FC & {Layout:LayoutType} = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>HI</main>

      <footer></footer>
    </div>
  );
}
Home.Layout= Layout
export default Home